### ISSUE TITLE
Getting "Error loading file!" Every Time I Try to Watch a Video

### ISSUE THREAD

**Issue by AetheralMeowstic** [RiiConnect24/RiiTube#3]
Yes, I did fresh reinstalls of both WiiMC and WiiMC-SS, yes, I've restarted my Wii, yes, I've restarted the hotspot that's literally always worked, no, I haven't given my hotspot a password, no, literally everything else having to do with RiiConnect24 and WiiLink still works, no, I didn't change the RiiTube URL.

It's just that RiiTube is suddenly flat-out _refusing_ to play YouTube videos.

**Comment by larsenv** [comment]
This problem is fixed.

**Comment by MattTheTekie** [comment]
> This problem is fixed.

The issue happened again. @larsenv

**Comment by larsenv** [comment]
@MattTheTekie it works fine for me, what video are you trying?
